source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem "test-kitchen"
gem "kitchen-docker"
gem "kitchen-pester", :git => 'https://github.com/glennsarti/kitchen-pester.git', :branch => 'use-on-linux'

# Evaluate Gemfile.local and ~/.gemfile if they exist
extra_gemfiles = [
  "#{__FILE__}.local",
  File.join(Dir.home, '.gemfile'),
]

extra_gemfiles.each do |gemfile|
  if File.file?(gemfile) && File.readable?(gemfile)
    eval(File.read(gemfile), binding)
  end
end
